CREATE TABLE "kv_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "kv_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"value" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "kv_data_key_unique" UNIQUE("key")
);
--> statement-breakpoint
ALTER TABLE "user_posts" ALTER COLUMN "tags" SET DEFAULT '[]'::jsonb;