CREATE TABLE "url_shorter" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "url_shorter_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"url_slug" text NOT NULL,
	"linked_item" text NOT NULL,
	"by_user" text NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "url_shorter_url_slug_unique" UNIQUE("url_slug")
);
--> statement-breakpoint
ALTER TABLE "url_shorter" ADD CONSTRAINT "url_shorter_linked_item_user_posts_post_id_fk" FOREIGN KEY ("linked_item") REFERENCES "public"."user_posts"("post_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "url_shorter" ADD CONSTRAINT "url_shorter_by_user_user_id_fk" FOREIGN KEY ("by_user") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;