CREATE TABLE "collections" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "collections_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"collection_id" text NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"items" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"by_user" text NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "collections_collection_id_unique" UNIQUE("collection_id"),
	CONSTRAINT "collections_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "url_shorter" RENAME COLUMN "linked_item" TO "target_url";--> statement-breakpoint
ALTER TABLE "url_shorter" DROP CONSTRAINT "url_shorter_linked_item_user_posts_post_id_fk";
--> statement-breakpoint
ALTER TABLE "collections" ADD CONSTRAINT "collections_by_user_user_id_fk" FOREIGN KEY ("by_user") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;