import type { NextRequest } from "next/server";

export const GET = async (request: NextRequest) => {
  let res = "# robots.txt generated by the server.\n";
  res += "User-Agent: AddSearchBot\n Disallow: /\n";
  return new Response(res, {
    status: 200,
    headers: {
      "Content-Type": "text/plain",
    },
  });
};
