import type { NextRequest } from "next/server";
import { db, dorm, main_schema } from "../../../../../packages/db/src";

export const GET = async (request: NextRequest) => {
  const homePageStatus = await db
    .select()
    .from(main_schema.kvData)
    .where(dorm.eq(main_schema.kvData.key, "robotsTxtStatus"));

  if (String(homePageStatus[0].value) !== "false") {
    return new Response("", {
      status: 200,
      headers: {
        "Content-Type": "text/plain",
      },
    });
  }
  let res = "# robots.txt generated by the server.\n";
  res += "User-Agent: AddSearchBot\n Disallow: /\n";
  return new Response(res, {
    status: 200,
    headers: {
      "Content-Type": "text/plain",
    },
  });
};
